### Development environment configuration
[development.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[development.accounts]]
name = "me" # Required. Keys for this account will be saved to `./.stellar/identity`
default = true # Optional. Whether to use this account as the `--source` for commands that need one.

[development.contracts]

[development.contracts.no_loss_lottery]
client = true
# Constructor arguments:
# - admin: The admin account
# - token: Native XLM on testnet
# - ticket_amount: Fixed amount per ticket in stroops (10000000 = 1 XLM)
constructor_args = """
--admin GBEFGOMLLAWHNSZIED3VWGM7KP6VPE6LV662TRI2ZLYLEBD3KZZZC2MP
--token CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU
--ticket_amount 100000000
--blend_address CDDG7DLOWSHRYQ2HWGZEZ4UTR7LPTKFFHN3QUCSZEXOWOPARMONX6T65
"""

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]

### Production environment configuration
[production.network]
rpc-url = "https://rpc.lightsail.network/"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "deployer"
default = true

[production.contracts]

[production.contracts.no_loss_lottery]
id = "CDID2FBEZOSICXXQ25NBJFFS5MT3JWYOD3P6D3HCJGTXOFIQZZD42TJH"
client = true
# Constructor arguments:
# - admin: The admin account
# - token: Native XLM on testnet
# - ticket_amount: Fixed amount per ticket in stroops (10000000 = 1 XLM)
# - blend_address: Contract address of blend pool
constructor_args = """
--admin GCSN5ABOTISYQ3W76WGJKBX3BDNNHB6UVTYUDWHXJ4TREJ4WH7VTKEFM
--token CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75
--ticket_amount 100000000
--blend_address CCCCIQSDILITHMM7PBSLVDT5MISSY7R26MNZXCX4H7J5JQ5FPIYOGYFS
"""
